version: "3.9"

services:
  nginx:
    container_name: test_nginx
    image: nginx:1.23
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: test_php
    image: fpm-8.3:psql
    volumes:
      - ./:/var/www
#      - ./.bashrc:/root/.bashrc
      - ./php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php.ini-production:/usr/local/etc/php/php.ini-production
      - ./php.ini-production:/usr/local/etc/php/php.ini
    working_dir: /var/www
#    command:
#      - /test.sh


#  postgres:
#    container_name: postgres_lab
#    image: postgres:14-alpine
#    environment:
#      - POSTGRES_DB=sf6v4basicdb
#      - POSTGRES_PASSWORD=pgpwd
#      - POSTGRES_USER=pguser
#    volumes:
#      - /home/leo/projectData/commonUse/db/postgres14/dataDir/mySql/data:/var/lib/postgresql/data:rw
#    ports:
#      - target: 5432
#        published: 5432
#        protocol: tcp
